name: sub_routes (GoRoute-project_04)
description: This project is a part of the go_route series.
homepage: https://github.com/rahulsharmadev-community/youtube-tutorials/tree/master/project_04--go_route

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
